//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "sugarsoapBinding", Namespace = "http://www.sugarcrm.com/sugarcrm")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(upgrade_history))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(user_detail))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(contact_detail))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(id_mod))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(entry_value))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(name_value))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(field))]
public partial class sugarsoap : System.Web.Services.Protocols.SoapHttpClientProtocol {

    /// <remarks/>
    public sugarsoap() {
        this.Url = "http://demo.sugarcrm.com/sugarcrm/soap.php";
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/is_user_admin", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public int is_user_admin(string session) {
        object[] results = this.Invoke("is_user_admin", new object[] {
                    session});
        return ((int)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/login", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entry_result login(user_auth user_auth, string application_name) {
        object[] results = this.Invoke("login", new object[] {
                    user_auth,
                    application_name});
        return ((set_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/is_loopback", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public int is_loopback() {
        object[] results = this.Invoke("is_loopback", new object[0]);
        return ((int)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/seamless_login", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public int seamless_login(string session) {
        object[] results = this.Invoke("seamless_login", new object[] {
                    session});
        return ((int)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_entry_list", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_list_result get_entry_list(string session, string module_name, string query, string order_by, int offset, string[] select_fields, int max_results, int deleted) {
        object[] results = this.Invoke("get_entry_list", new object[] {
                    session,
                    module_name,
                    query,
                    order_by,
                    offset,
                    select_fields,
                    max_results,
                    deleted});
        return ((get_entry_list_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_entry", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_result get_entry(string session, string module_name, string id, string[] select_fields) {
        object[] results = this.Invoke("get_entry", new object[] {
                    session,
                    module_name,
                    id,
                    select_fields});
        return ((get_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_entries", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_result get_entries(string session, string module_name, string[] ids, string[] select_fields) {
        object[] results = this.Invoke("get_entries", new object[] {
                    session,
                    module_name,
                    ids,
                    select_fields});
        return ((get_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_entry", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entry_result set_entry(string session, string module_name, name_value[] name_value_list) {
        object[] results = this.Invoke("set_entry", new object[] {
                    session,
                    module_name,
                    name_value_list});
        return ((set_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_entries", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entries_result set_entries(string session, string module_name, name_value[][] name_value_lists) {
        object[] results = this.Invoke("set_entries", new object[] {
                    session,
                    module_name,
                    name_value_lists});
        return ((set_entries_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_note_attachment", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entry_result set_note_attachment(string session, note_attachment note) {
        object[] results = this.Invoke("set_note_attachment", new object[] {
                    session,
                    note});
        return ((set_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_note_attachment", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public return_note_attachment get_note_attachment(string session, string id) {
        object[] results = this.Invoke("get_note_attachment", new object[] {
                    session,
                    id});
        return ((return_note_attachment)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/relate_note_to_module", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public error_value relate_note_to_module(string session, string note_id, string module_name, string module_id) {
        object[] results = this.Invoke("relate_note_to_module", new object[] {
                    session,
                    note_id,
                    module_name,
                    module_id});
        return ((error_value)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_related_notes", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_result get_related_notes(string session, string module_name, string module_id, string[] select_fields) {
        object[] results = this.Invoke("get_related_notes", new object[] {
                    session,
                    module_name,
                    module_id,
                    select_fields});
        return ((get_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/logout", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public error_value logout(string session) {
        object[] results = this.Invoke("logout", new object[] {
                    session});
        return ((error_value)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_module_fields", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public module_fields get_module_fields(string session, string module_name) {
        object[] results = this.Invoke("get_module_fields", new object[] {
                    session,
                    module_name});
        return ((module_fields)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_available_modules", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public module_list get_available_modules(string session) {
        object[] results = this.Invoke("get_available_modules", new object[] {
                    session});
        return ((module_list)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/update_portal_user", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public error_value update_portal_user(string session, string portal_name, name_value[] name_value_list) {
        object[] results = this.Invoke("update_portal_user", new object[] {
                    session,
                    portal_name,
                    name_value_list});
        return ((error_value)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/test", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string test(string @string) {
        object[] results = this.Invoke("test", new object[] {
                    @string});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_user_id", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string get_user_id(string session) {
        object[] results = this.Invoke("get_user_id", new object[] {
                    session});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_user_team_id", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string get_user_team_id(string session) {
        object[] results = this.Invoke("get_user_team_id", new object[] {
                    session});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_server_time", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string get_server_time() {
        object[] results = this.Invoke("get_server_time", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_gmt_time", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string get_gmt_time() {
        object[] results = this.Invoke("get_gmt_time", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_sugar_flavor", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string get_sugar_flavor() {
        object[] results = this.Invoke("get_sugar_flavor", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_server_version", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string get_server_version() {
        object[] results = this.Invoke("get_server_version", new object[0]);
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_relationships", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_relationships_result get_relationships(string session, string module_name, string module_id, string related_module, string related_module_query, int deleted) {
        object[] results = this.Invoke("get_relationships", new object[] {
                    session,
                    module_name,
                    module_id,
                    related_module,
                    related_module_query,
                    deleted});
        return ((get_relationships_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_relationship", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public error_value set_relationship(string session, set_relationship_value set_relationship_value) {
        object[] results = this.Invoke("set_relationship", new object[] {
                    session,
                    set_relationship_value});
        return ((error_value)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_relationships", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_relationship_list_result set_relationships(string session, set_relationship_value[] set_relationship_list) {
        object[] results = this.Invoke("set_relationships", new object[] {
                    session,
                    set_relationship_list});
        return ((set_relationship_list_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_document_revision", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entry_result set_document_revision(string session, document_revision note) {
        object[] results = this.Invoke("set_document_revision", new object[] {
                    session,
                    note});
        return ((set_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/search_by_module", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_list_result search_by_module(string user_name, string password, string search_string, string[] modules, int offset, int max_results) {
        object[] results = this.Invoke("search_by_module", new object[] {
                    user_name,
                    password,
                    search_string,
                    modules,
                    offset,
                    max_results});
        return ((get_entry_list_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_mailmerge_document", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_sync_result_encoded get_mailmerge_document(string session, string file_name, string[] fields) {
        object[] results = this.Invoke("get_mailmerge_document", new object[] {
                    session,
                    file_name,
                    fields});
        return ((get_sync_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_mailmerge_document2", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_mailmerge_document_result get_mailmerge_document2(string session, string file_name, string[] fields) {
        object[] results = this.Invoke("get_mailmerge_document2", new object[] {
                    session,
                    file_name,
                    fields});
        return ((get_mailmerge_document_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_document_revision", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public return_document_revision get_document_revision(string session, string i) {
        object[] results = this.Invoke("get_document_revision", new object[] {
                    session,
                    i});
        return ((return_document_revision)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_campaign_merge", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public error_value set_campaign_merge(string session, string[] targets, string campaign_id) {
        object[] results = this.Invoke("set_campaign_merge", new object[] {
                    session,
                    targets,
                    campaign_id});
        return ((error_value)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_entries_count", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entries_count_result get_entries_count(string session, string module_name, string query, int deleted) {
        object[] results = this.Invoke("get_entries_count", new object[] {
                    session,
                    module_name,
                    query,
                    deleted});
        return ((get_entries_count_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/set_entries_details", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entries_detail_result set_entries_details(string session, string module_name, name_value[][] name_value_lists, string[] select_fields) {
        object[] results = this.Invoke("set_entries_details", new object[] {
                    session,
                    module_name,
                    name_value_lists,
                    select_fields});
        return ((set_entries_detail_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/sync_get_modified_relationships", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_list_result_encoded sync_get_modified_relationships(string session, string module_name, string related_module, string from_date, string to_date, int offset, int max_results, int deleted, string module_id, string[] select_fields, string[] ids, string relationship_name, string deletion_date, int php_serialize) {
        object[] results = this.Invoke("sync_get_modified_relationships", new object[] {
                    session,
                    module_name,
                    related_module,
                    from_date,
                    to_date,
                    offset,
                    max_results,
                    deleted,
                    module_id,
                    select_fields,
                    ids,
                    relationship_name,
                    deletion_date,
                    php_serialize});
        return ((get_entry_list_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_modified_entries", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_sync_result_encoded get_modified_entries(string session, string module_name, string[] ids, string[] select_fields) {
        object[] results = this.Invoke("get_modified_entries", new object[] {
                    session,
                    module_name,
                    ids,
                    select_fields});
        return ((get_sync_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_attendee_list", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_sync_result_encoded get_attendee_list(string session, string module_name, string id) {
        object[] results = this.Invoke("get_attendee_list", new object[] {
                    session,
                    module_name,
                    id});
        return ((get_sync_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/create_session", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string create_session(string user_name, string password) {
        object[] results = this.Invoke("create_session", new object[] {
                    user_name,
                    password});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/end_session", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string end_session(string user_name) {
        object[] results = this.Invoke("end_session", new object[] {
                    user_name});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/contact_by_email", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public contact_detail[] contact_by_email(string user_name, string password, string email_address) {
        object[] results = this.Invoke("contact_by_email", new object[] {
                    user_name,
                    password,
                    email_address});
        return ((contact_detail[])(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_contact_relationships", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public contact_detail[] get_contact_relationships(string user_name, string password, string id) {
        object[] results = this.Invoke("get_contact_relationships", new object[] {
                    user_name,
                    password,
                    id});
        return ((contact_detail[])(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/user_list", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public user_detail[] user_list(string user_name, string password) {
        object[] results = this.Invoke("user_list", new object[] {
                    user_name,
                    password});
        return ((user_detail[])(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/search", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public contact_detail[] search(string user_name, string password, string name) {
        object[] results = this.Invoke("search", new object[] {
                    user_name,
                    password,
                    name});
        return ((contact_detail[])(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/track_email", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string track_email(string user_name, string password, string parent_id, string contact_ids, [System.Xml.Serialization.SoapElementAttribute(DataType = "date")] System.DateTime date_sent, string email_subject, string email_body) {
        object[] results = this.Invoke("track_email", new object[] {
                    user_name,
                    password,
                    parent_id,
                    contact_ids,
                    date_sent,
                    email_subject,
                    email_body});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/create_contact", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string create_contact(string user_name, string password, string first_name, string last_name, string email_address) {
        object[] results = this.Invoke("create_contact", new object[] {
                    user_name,
                    password,
                    first_name,
                    last_name,
                    email_address});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/create_lead", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string create_lead(string user_name, string password, string first_name, string last_name, string email_address) {
        object[] results = this.Invoke("create_lead", new object[] {
                    user_name,
                    password,
                    first_name,
                    last_name,
                    email_address});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/create_account", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string create_account(string user_name, string password, string name, string phone, string website) {
        object[] results = this.Invoke("create_account", new object[] {
                    user_name,
                    password,
                    name,
                    phone,
                    website});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/create_opportunity", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string create_opportunity(string user_name, string password, string name, string amount) {
        object[] results = this.Invoke("create_opportunity", new object[] {
                    user_name,
                    password,
                    name,
                    amount});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/create_case", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public string create_case(string user_name, string password, string name) {
        object[] results = this.Invoke("create_case", new object[] {
                    user_name,
                    password,
                    name});
        return ((string)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/sync_get_entries", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_list_result_encoded sync_get_entries(string session, string module_name, string from_date, string to_date, int offset, int max_results, string[] select_fields, string query, int deleted) {
        object[] results = this.Invoke("sync_get_entries", new object[] {
                    session,
                    module_name,
                    from_date,
                    to_date,
                    offset,
                    max_results,
                    select_fields,
                    query,
                    deleted});
        return ((get_entry_list_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/sync_set_entries", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public sync_set_entries_encoded sync_set_entries(string session, string module_name, string from_date, string to_date, string sync_entry_list, int deleted) {
        object[] results = this.Invoke("sync_set_entries", new object[] {
                    session,
                    module_name,
                    from_date,
                    to_date,
                    sync_entry_list,
                    deleted});
        return ((sync_set_entries_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/sync_get_relationships", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_entry_list_result_encoded sync_get_relationships(string session, string module_name, string related_module, string from_date, string to_date, int offset, int max_results, int deleted) {
        object[] results = this.Invoke("sync_get_relationships", new object[] {
                    session,
                    module_name,
                    related_module,
                    from_date,
                    to_date,
                    offset,
                    max_results,
                    deleted});
        return ((get_entry_list_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/sync_set_relationships", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public sync_set_entries_encoded sync_set_relationships(string session, string module_name, string related_module, string from_date, string to_date, string sync_entry_list) {
        object[] results = this.Invoke("sync_set_relationships", new object[] {
                    session,
                    module_name,
                    related_module,
                    from_date,
                    to_date,
                    sync_entry_list});
        return ((sync_set_entries_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/sudo_user", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public error_value sudo_user(string session, string user_name) {
        object[] results = this.Invoke("sudo_user", new object[] {
                    session,
                    user_name});
        return ((error_value)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_system_status", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entry_result get_system_status(string session, string unique_key) {
        object[] results = this.Invoke("get_system_status", new object[] {
                    session,
                    unique_key});
        return ((set_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_unique_system_id", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public set_entry_result get_unique_system_id(string session, string unique_key, string system_name, string install_method) {
        object[] results = this.Invoke("get_unique_system_id", new object[] {
                    session,
                    unique_key,
                    system_name,
                    install_method});
        return ((set_entry_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/offline_client_available", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public int offline_client_available() {
        object[] results = this.Invoke("offline_client_available", new object[0]);
        return ((int)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_quick_sync_data", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_quick_sync_result_encoded get_quick_sync_data(string session, string module_name, string related_module_name, int start, int count, string db_type, int deleted) {
        object[] results = this.Invoke("get_quick_sync_data", new object[] {
                    session,
                    module_name,
                    related_module_name,
                    start,
                    count,
                    db_type,
                    deleted});
        return ((get_quick_sync_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_encoded_file", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public encoded_file get_encoded_file(string session, string filename) {
        object[] results = this.Invoke("get_encoded_file", new object[] {
                    session,
                    filename});
        return ((encoded_file)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_encoded_zip_file", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_sync_result_encoded get_encoded_zip_file(string session, encoded_file md5file, string last_sync, int is_md5_sync) {
        object[] results = this.Invoke("get_encoded_zip_file", new object[] {
                    session,
                    md5file,
                    last_sync,
                    is_md5_sync});
        return ((get_sync_result_encoded)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_required_upgrades", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public upgrade_history_result get_required_upgrades(string session, upgrade_history[] client_upgrade_history, string client_version) {
        object[] results = this.Invoke("get_required_upgrades", new object[] {
                    session,
                    client_upgrade_history,
                    client_version});
        return ((upgrade_history_result)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_disc_client_file_list", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public encoded_file get_disc_client_file_list(string session) {
        object[] results = this.Invoke("get_disc_client_file_list", new object[] {
                    session});
        return ((encoded_file)(results[0]));
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://demo.sugarcrm.com/sugarcrm/soap.php/get_encoded_portal_zip_file", RequestNamespace = "http://www.sugarcrm.com/sugarcrm", ResponseNamespace = "http://www.sugarcrm.com/sugarcrm")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public get_sync_result_encoded get_encoded_portal_zip_file(string session, encoded_file md5file, string last_sync, int is_md5_sync) {
        object[] results = this.Invoke("get_encoded_portal_zip_file", new object[] {
                    session,
                    md5file,
                    last_sync,
                    is_md5_sync});
        return ((get_sync_result_encoded)(results[0]));
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class user_auth {

    private string user_nameField;

    private string passwordField;

    private string versionField;

    /// <remarks/>
    public string user_name {
        get {
            return this.user_nameField;
        }
        set {
            this.user_nameField = value;
        }
    }

    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class upgrade_history_result {

    private upgrade_history[] upgrade_history_listField;

    private error_value errorField;

    /// <remarks/>
    public upgrade_history[] upgrade_history_list {
        get {
            return this.upgrade_history_listField;
        }
        set {
            this.upgrade_history_listField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class upgrade_history {

    private string idField;

    private string filenameField;

    private string md5Field;

    private string typeField;

    private string statusField;

    private string versionField;

    private string date_enteredField;

    private error_value errorField;

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }

    /// <remarks/>
    public string md5 {
        get {
            return this.md5Field;
        }
        set {
            this.md5Field = value;
        }
    }

    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }

    /// <remarks/>
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }

    /// <remarks/>
    public string date_entered {
        get {
            return this.date_enteredField;
        }
        set {
            this.date_enteredField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class error_value {

    private string numberField;

    private string nameField;

    private string descriptionField;

    /// <remarks/>
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }

    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class encoded_file {

    private string filenameField;

    private string md5Field;

    private string dataField;

    private error_value errorField;

    /// <remarks/>
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }

    /// <remarks/>
    public string md5 {
        get {
            return this.md5Field;
        }
        set {
            this.md5Field = value;
        }
    }

    /// <remarks/>
    public string data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_quick_sync_result_encoded {

    private string resultField;

    private int result_countField;

    private int next_offsetField;

    private int total_countField;

    private error_value errorField;

    /// <remarks/>
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }

    /// <remarks/>
    public int result_count {
        get {
            return this.result_countField;
        }
        set {
            this.result_countField = value;
        }
    }

    /// <remarks/>
    public int next_offset {
        get {
            return this.next_offsetField;
        }
        set {
            this.next_offsetField = value;
        }
    }

    /// <remarks/>
    public int total_count {
        get {
            return this.total_countField;
        }
        set {
            this.total_countField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class sync_set_entries_encoded {

    private string conflictsField;

    private string statusField;

    private string[] idsField;

    private error_value errorField;

    /// <remarks/>
    public string conflicts {
        get {
            return this.conflictsField;
        }
        set {
            this.conflictsField = value;
        }
    }

    /// <remarks/>
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }

    /// <remarks/>
    public string[] ids {
        get {
            return this.idsField;
        }
        set {
            this.idsField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class user_detail {

    private string email_addressField;

    private string user_nameField;

    private string first_nameField;

    private string last_nameField;

    private string departmentField;

    private string idField;

    private string titleField;

    /// <remarks/>
    public string email_address {
        get {
            return this.email_addressField;
        }
        set {
            this.email_addressField = value;
        }
    }

    /// <remarks/>
    public string user_name {
        get {
            return this.user_nameField;
        }
        set {
            this.user_nameField = value;
        }
    }

    /// <remarks/>
    public string first_name {
        get {
            return this.first_nameField;
        }
        set {
            this.first_nameField = value;
        }
    }

    /// <remarks/>
    public string last_name {
        get {
            return this.last_nameField;
        }
        set {
            this.last_nameField = value;
        }
    }

    /// <remarks/>
    public string department {
        get {
            return this.departmentField;
        }
        set {
            this.departmentField = value;
        }
    }

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class contact_detail {

    private string email_addressField;

    private string name1Field;

    private string name2Field;

    private string associationField;

    private string idField;

    private string msi_idField;

    private string typeField;

    /// <remarks/>
    public string email_address {
        get {
            return this.email_addressField;
        }
        set {
            this.email_addressField = value;
        }
    }

    /// <remarks/>
    public string name1 {
        get {
            return this.name1Field;
        }
        set {
            this.name1Field = value;
        }
    }

    /// <remarks/>
    public string name2 {
        get {
            return this.name2Field;
        }
        set {
            this.name2Field = value;
        }
    }

    /// <remarks/>
    public string association {
        get {
            return this.associationField;
        }
        set {
            this.associationField = value;
        }
    }

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string msi_id {
        get {
            return this.msi_idField;
        }
        set {
            this.msi_idField = value;
        }
    }

    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_entry_list_result_encoded {

    private int result_countField;

    private int next_offsetField;

    private int total_countField;

    private string[] field_listField;

    private string entry_listField;

    private error_value errorField;

    /// <remarks/>
    public int result_count {
        get {
            return this.result_countField;
        }
        set {
            this.result_countField = value;
        }
    }

    /// <remarks/>
    public int next_offset {
        get {
            return this.next_offsetField;
        }
        set {
            this.next_offsetField = value;
        }
    }

    /// <remarks/>
    public int total_count {
        get {
            return this.total_countField;
        }
        set {
            this.total_countField = value;
        }
    }

    /// <remarks/>
    public string[] field_list {
        get {
            return this.field_listField;
        }
        set {
            this.field_listField = value;
        }
    }

    /// <remarks/>
    public string entry_list {
        get {
            return this.entry_listField;
        }
        set {
            this.entry_listField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class set_entries_detail_result {

    private name_value[][] name_value_listsField;

    private error_value errorField;

    /// <remarks/>
    public name_value[][] name_value_lists {
        get {
            return this.name_value_listsField;
        }
        set {
            this.name_value_listsField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class name_value {

    private string nameField;

    private string valueField;

    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_entries_count_result {

    private int result_countField;

    private error_value errorField;

    /// <remarks/>
    public int result_count {
        get {
            return this.result_countField;
        }
        set {
            this.result_countField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class return_document_revision {

    private document_revision document_revisionField;

    private error_value errorField;

    /// <remarks/>
    public document_revision document_revision {
        get {
            return this.document_revisionField;
        }
        set {
            this.document_revisionField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class document_revision {

    private string idField;

    private string document_nameField;

    private string revisionField;

    private string filenameField;

    private string fileField;

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string document_name {
        get {
            return this.document_nameField;
        }
        set {
            this.document_nameField = value;
        }
    }

    /// <remarks/>
    public string revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }

    /// <remarks/>
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }

    /// <remarks/>
    public string file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_mailmerge_document_result {

    private string htmlField;

    private name_value[] name_value_listField;

    private error_value errorField;

    /// <remarks/>
    public string html {
        get {
            return this.htmlField;
        }
        set {
            this.htmlField = value;
        }
    }

    /// <remarks/>
    public name_value[] name_value_list {
        get {
            return this.name_value_listField;
        }
        set {
            this.name_value_listField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_sync_result_encoded {

    private string resultField;

    private error_value errorField;

    /// <remarks/>
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class set_relationship_list_result {

    private int createdField;

    private int failedField;

    private error_value errorField;

    /// <remarks/>
    public int created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }

    /// <remarks/>
    public int failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class set_relationship_value {

    private string module1Field;

    private string module1_idField;

    private string module2Field;

    private string module2_idField;

    /// <remarks/>
    public string module1 {
        get {
            return this.module1Field;
        }
        set {
            this.module1Field = value;
        }
    }

    /// <remarks/>
    public string module1_id {
        get {
            return this.module1_idField;
        }
        set {
            this.module1_idField = value;
        }
    }

    /// <remarks/>
    public string module2 {
        get {
            return this.module2Field;
        }
        set {
            this.module2Field = value;
        }
    }

    /// <remarks/>
    public string module2_id {
        get {
            return this.module2_idField;
        }
        set {
            this.module2_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class id_mod {

    private string idField;

    private string date_modifiedField;

    private int deletedField;

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string date_modified {
        get {
            return this.date_modifiedField;
        }
        set {
            this.date_modifiedField = value;
        }
    }

    /// <remarks/>
    public int deleted {
        get {
            return this.deletedField;
        }
        set {
            this.deletedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_relationships_result {

    private id_mod[] idsField;

    private error_value errorField;

    /// <remarks/>
    public id_mod[] ids {
        get {
            return this.idsField;
        }
        set {
            this.idsField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class module_list {

    private string[] modulesField;

    private error_value errorField;

    /// <remarks/>
    public string[] modules {
        get {
            return this.modulesField;
        }
        set {
            this.modulesField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class module_fields {

    private string module_nameField;

    private field[] module_fields1Field;

    private error_value errorField;

    /// <remarks/>
    public string module_name {
        get {
            return this.module_nameField;
        }
        set {
            this.module_nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute("module_fields")]
    public field[] module_fields1 {
        get {
            return this.module_fields1Field;
        }
        set {
            this.module_fields1Field = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class field {

    private string nameField;

    private string typeField;

    private string labelField;

    private int requiredField;

    private name_value[] optionsField;

    private string default_valueField;

    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }

    /// <remarks/>
    public int required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }

    /// <remarks/>
    public name_value[] options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }

    /// <remarks/>
    public string default_value {
        get {
            return this.default_valueField;
        }
        set {
            this.default_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class return_note_attachment {

    private note_attachment note_attachmentField;

    private error_value errorField;

    /// <remarks/>
    public note_attachment note_attachment {
        get {
            return this.note_attachmentField;
        }
        set {
            this.note_attachmentField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class note_attachment {

    private string idField;

    private string filenameField;

    private string fileField;

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }

    /// <remarks/>
    public string file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class set_entries_result {

    private string[] idsField;

    private error_value errorField;

    /// <remarks/>
    public string[] ids {
        get {
            return this.idsField;
        }
        set {
            this.idsField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_entry_result {

    private field[] field_listField;

    private entry_value[] entry_listField;

    private error_value errorField;

    /// <remarks/>
    public field[] field_list {
        get {
            return this.field_listField;
        }
        set {
            this.field_listField = value;
        }
    }

    /// <remarks/>
    public entry_value[] entry_list {
        get {
            return this.entry_listField;
        }
        set {
            this.entry_listField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class entry_value {

    private string idField;

    private string module_nameField;

    private name_value[] name_value_listField;

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string module_name {
        get {
            return this.module_nameField;
        }
        set {
            this.module_nameField = value;
        }
    }

    /// <remarks/>
    public name_value[] name_value_list {
        get {
            return this.name_value_listField;
        }
        set {
            this.name_value_listField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class get_entry_list_result {

    private int result_countField;

    private int next_offsetField;

    private field[] field_listField;

    private entry_value[] entry_listField;

    private error_value errorField;

    /// <remarks/>
    public int result_count {
        get {
            return this.result_countField;
        }
        set {
            this.result_countField = value;
        }
    }

    /// <remarks/>
    public int next_offset {
        get {
            return this.next_offsetField;
        }
        set {
            this.next_offsetField = value;
        }
    }

    /// <remarks/>
    public field[] field_list {
        get {
            return this.field_listField;
        }
        set {
            this.field_listField = value;
        }
    }

    /// <remarks/>
    public entry_value[] entry_list {
        get {
            return this.entry_listField;
        }
        set {
            this.entry_listField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://www.sugarcrm.com/sugarcrm")]
public partial class set_entry_result {

    private string idField;

    private error_value errorField;

    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    public error_value error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}
